Implement static pre-evaluation check, instead of `post_init` check.
dfm/tinygp pull request #146
Opened 2023-01-12 20:57 UTC by femtomc

Addresses #140.

2023-01-12 20:58 UTC, femtomc commented
@dfm When you have some time, consider the pattern I'm introducing into the `Kernel` ABC -- instead of `evaluate`, overloads define `__evaluate__` and `evaluate` calls `__static_evaluate_check__` and then `__evaluate__`.

2023-01-13 19:12 UTC, dfm commented
Thanks for this! I think I understand what's going on now. What do you think about instead just moving all the checks that are currently in `__post_init__` to the individual `evaluate` functions directly? It seems like it wouldn't be too painful to do that and more backwards compatible?

2023-01-13 19:13 UTC, dfm requested changes

2023-01-13 19:13 UTC, dfm commented on src/tinygp/kernels/stationary.py
> -        assert self.gamma is not None
This is in here for mypy reasons so better not to remove it, I'd say!

2023-01-13 19:13 UTC, dfm commented on src/tinygp/kernels/stationary.py
> -        assert self.alpha is not None
Same as above!

2023-01-14 20:12 UTC, femtomc commented
Sure! That sounds great!

I was attempting to implement something which would minimize replicating calls — the problem is that there’s not a super convenient way to add a pre-check to a function which a user can define for their implementation — without doing the weird indirection in my initial PR.

I’ll change it to your suggestion!

2023-01-20 15:54 UTC, closed without merging